services:
  stream_announcer:
    image: burnysc2/twitch_stream_announcer:latest
    command: "./main"
    pull_policy: never
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 2048M
      restart_policy:
        # Wait 1m before restarting, seems to be ignored?!
        delay: 1m
        condition: any
    restart: always
    env_file:
      - .env
