VERSION 0.6
# earthly +all --PYTHONVERSION=3.12
ARG PYTHONVERSION=3.12
FROM ghcr.io/astral-sh/uv:python${PYTHONVERSION}-bookworm-slim
WORKDIR /root/stream_announcer

install-dev:
    COPY uv.lock pyproject.toml ./
    RUN uv sync --frozen --no-cache --no-install-project
    COPY src /root/fastapi_server/src

format:
    # Run on host system instead of inside a container
    LOCALLY
    # Requirements:
    # pip install uv
    # uv sync
    
    # Convert single to double quotes
    RUN uv run ruff check . --select Q --fix
    # Remove unused imports
    RUN uv run ruff check . --select F --fix
    # Sort imports
    RUN uv run ruff check . --select I --fix
    # Format code
    RUN uv run ruff format .

# Check if files are correctly formatted
format-check:
    FROM +install-dev
    RUN uv run ruff format . --check --diff

# Ignore errors via "# noqa: F841"
lint:
    FROM +install-dev
    RUN uv run ruff check .

# Ignore errors via "# pyre-fixme[11]"
pyre:
    FROM +install-dev
    COPY .pyre_configuration /root/stream_announcer/.pyre_configuration
    RUN uv run pyre

# pytest:
#     FROM +install-dev
#     RUN uv run pytest test

pre-commit:
    BUILD +format-check
    BUILD +lint
    BUILD +pyre

all:
    BUILD +pre-commit
    #BUILD +pytest
