networks:
  '{{secrets.TRAEFIK_NETWORK}}':
    external: true

# https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/get-started/create-local-tunnel/
# https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/tunnel-run-parameters/
# https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/local-management/configuration-file/
services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    pull_policy: always
    command: tunnel --no-autoupdate run
    networks:
    - '{{ secrets.TRAEFIK_NETWORK }}'
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN={{ CLOUDFLARE_TUNNEL_TOKEN }}
