
# https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/tunnel-run-parameters/
# https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/local-management/configuration-file/
# Execute with
# ansible-playbook setup_cloudflared.yml -i ../hosts -i /home/burny/syncthing/secrets/ansible_secrets/.ansible_secrets
- name: Create service
  hosts: server_group2
  vars:
    USERNAME: "{{ secrets.CLOUDFLARED.USERNAME }}"
  tasks:
    - name: Create group
      ansible.builtin.group:
        name: "{{ USERNAME }}"
        state: present

    - name: Create user
      ansible.builtin.user:
        name: "{{ USERNAME }}"
        groups:
          - "{{ USERNAME }}"
          - docker
        shell: "{{ secrets.DEFAULT_SHELL }}"
        
    - name: Copy docker-compose.yml file
      template:
        src: docker-compose.yml
        dest: /home/{{ USERNAME }}/docker-compose.yml

    - name: Run `docker-compose up` again
      community.docker.docker_compose_v2:
        project_src: /home/{{ USERNAME }}
        state: restarted
