networks:
  '{{secrets.TRAFIK_NETWORK}}':
    external: true

# Don't forget to change IP in GUI from 127.0.0.1 to 0.0.0.0 if you want to expose it to the web
services:
  syncthing:
    container_name: syncthing
    hostname: syncthing
    restart: unless-stopped
    image: lscr.io/linuxserver/syncthing:latest
    volumes:
    - ./config:/config
    - ./data1:/data1
    environment:
    - PUID={{ USER_ID.stdout }}
    - PGID={{ GROUP_ID.stdout }}
    networks:
    - '{{ secrets.TRAFIK_NETWORK }}'
    labels:
    - traefik.enable=true
    - traefik.http.routers.{{ secrets.SYNCTHING.USERNAME }}.rule=Host(`{{ SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}`)
    - traefik.http.services.{{ secrets.SYNCTHING.USERNAME }}.loadbalancer.server.port={{ APPLICATION_PORT }}
    - traefik.http.routers.{{ secrets.SYNCTHING.USERNAME }}.tls=true
    - traefik.http.routers.{{ secrets.SYNCTHING.USERNAME }}.tls.certresolver=production
    - traefik.http.routers.{{ secrets.SYNCTHING.USERNAME }}.middlewares=authelia@docker
