networks:
  "{{secrets.TRAEFIK_NETWORK}}":
    external: true

# Don't forget to change IP in GUI from 127.0.0.1 to 0.0.0.0 if you want to expose it to the web
services:
  syncthing:
    container_name: syncthing
    hostname: syncthing
    restart: unless-stopped
    image: lscr.io/linuxserver/syncthing:latest
    volumes:
      - ./config:/config
      - ./data1:/data1
    environment:
      - PUID={{ USER_ID.stdout }}
      - PGID={{ GROUP_ID.stdout }}
    networks:
      - "{{ secrets.TRAEFIK_NETWORK }}"
    labels:
      - traefik.enable=true
      - traefik.http.routers.{{ USERNAME }}.entrypoints=web,websecure
      - traefik.http.routers.{{ USERNAME }}.rule=Host(`{{ SYNCTHING_URL }}`)
      - traefik.http.services.{{ USERNAME }}.loadbalancer.server.port={{ APPLICATION_PORT }}
      - traefik.http.routers.{{ USERNAME }}.tls=true
      - traefik.http.routers.{{ USERNAME }}.tls.certresolver=production
      - traefik.http.routers.{{ USERNAME }}.middlewares=authelia@docker
