services:
  registry:
    image: registry:2
    container_name: docker_registry
    restart: unless-stopped
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm
      # https://teplyheng.medium.com/how-to-completely-remove-docker-images-from-a-docker-registry-v2-76d8a26847ff
      # Delete untagged images from terminal:
      # docker exec docker_registry bin/registry garbage-collect -m /etc/docker/registry/config.yml
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    labels:
      - traefik.enable=true
      - traefik.http.routers.registry.entrypoints=web,websecure
      - traefik.http.routers.registry.rule=Host(`{{ secrets.DOCKER_REGISTRY.SUBDOMAIN }}.{{ secrets.MY_DOMAIN }}`)
      - traefik.http.services.registry.loadbalancer.server.port={{ APPLICATION_PORT }}
      - traefik.http.routers.registry.service=registry
      - traefik.http.routers.registry.tls=true
      - traefik.http.routers.registry.tls.certresolver=production
    networks:
      - "{{ secrets.TRAEFIK_NETWORK }}"
      
networks:
  "{{secrets.TRAEFIK_NETWORK}}":
    external: true
       
