networks:
  "{{ secrets.TRAEFIK_NETWORK }}":
    external: true

services:
  traefik:
    image: "traefik:v3.2"
    container_name: "traefik"
    hostname: "traefik"
    networks:
      - "{{ secrets.TRAEFIK_NETWORK }}"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network={{ secrets.TRAEFIK_NETWORK }}"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.pgsql.address=:5432"
    volumes:
      # ssl is managed by cloudflarez
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`{{ TRAEFIK_URL }}`)
      - traefik.http.routers.api.entryPoints=web,websecure
      - traefik.http.routers.api.service=api@internal
      - traefik.http.services.api.loadbalancer.server.port={{ APPLICATION_PORT }}
